name: Lint via DotNet
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/parts/cache/
      - name: 'Run dotnet checks'
        run: |
          dotnet build -t:Lint -c:Release
