name: All packages test

on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - 'ubuntu-latest'
          # TODO: Windows tests don't seem to work (though everything else does)
          # - 'windows-latest'
          - 'macos-latest'
    runs-on: ${{ matrix.os }}
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/parts/cache/

      ###########
      # BUILD
      - name: Restore dependencies
        run: dotnet restore --locked-mode
      - name: Build
        run: |
          dotnet build --no-restore --configuration Release

      ###########
      # TEST
      - shell: pwsh
        run: |
          Get-Command pnpm | ConvertTo-Json
      - name: Test
        run: |
          dotnet test --verbosity normal --configuration Release --no-build --collect:"XPlat Code Coverage"
      - name: 'Upload Code Coverage'
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: ./lib/*/TestResults/*/coverage.cobertura.xml
          retention-days: 7
