name: All packages test

on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/parts/cache/

      ###########
      # BUILD
      - name: Restore dependencies
        run: dotnet restore --locked-mode
      - name: Build
        run: |
          if [[ $VERSION_SUFFIX ]]; then
            VERSION_SUFFIX_PARAM="--version-suffix sha.$VERSION_SUFFIX"
          else
            VERSION_SUFFIX_PARAM=''
          fi
          dotnet build --no-restore --configuration Release ${VERSION_SUFFIX_PARAM}
        env:
          VERSION_SUFFIX: ${{ github.ref != 'refs/heads/main' && github.sha || '' }}

      ###########
      # TEST
      - name: Test
        run: |
          if [[ $VERSION_SUFFIX ]]; then
            VERSION_SUFFIX_PARAM="-p:VersionSuffix=sha.$VERSION_SUFFIX"
          else
            VERSION_SUFFIX_PARAM=''
          fi
          dotnet test --verbosity normal ${VERSION_SUFFIX_PARAM} --configuration Release --collect:"XPlat Code Coverage"
        env:
          VERSION_SUFFIX: ${{ github.ref != 'refs/heads/main' && github.sha || '' }}
      - name: 'Upload Code Coverage'
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: ./lib/*/TestResults/*/coverage.cobertura.xml
          retention-days: 7
